### ISSUE TITLE
[Feature Request] Use custom command as base command

### ISSUE THREAD

**Issue by Jack1789** [clechasseur/pathcopycopy#92] opened 2019-09-17 05:32 UTC
Hello, some minutes ago I wanted to create a new custom command, which should had been based on an already present one, but I couldn't do it. So, it would good if there is the chance of either copying or using as a base command, a previously customized one. That way, a new one have not to be replicated from scratch, in case of just wanting to do some further modifications.

Thanks.

**Comment by clechasseur** [comment] 2019-09-17 13:14
The "funny" thing is that there is no technical problem with having a custom command be the base command of another - it just isn't enabled in the UI because it caused some issues when I developed custom commands in the first place... I'll have to review this and try to remember what the problem(s) was(were).

**Comment by clechasseur** [comment] 2019-09-18 15:04
I remembered what the problem is. If a custom command has a NEW custom command as base command, previews won't work properly. This is a bit complex to fix, but I think it's doable. So this will act as a "note to self" 😄

**Comment by clechasseur** [comment] 2019-09-29 23:40
I've thought about this some more. In addition to the preview issue, there is also the issue of a command being based off itself (easy to detect and prevent) or of forming a loop of commands (much harder to detect and prevent). This will need some serious thinking on how to implement safeguards for this right.

Leaving this open, but won't work on this in 17.1.

**Comment by clechasseur** [comment] 2020-01-20 02:25
This has been implemented and will be part of the next major release (tentatively 18.0).

**Closed by clechasseur** 2020-01-20 02:25 UTC
Labels: enhancement

**Comment by Jack1789** [comment] 2020-01-20 23:02
Excellent news!!!

Thanks. :)
