### ISSUE TITLE
[FEATURE] Add "File" and "Folder" headers with option to post short name of file as hyperlink.

### ISSUE THREAD

**Issue by Rafaelmartinezhok** [clechasseur/pathcopycopy#156] opened 2022-08-03 15:04 UTC
**Is your feature request related to a problem? Please describe.**
Another firm uses an add-in that they built called **_Mail Manager_**. It has this great function that will copy and paste the file name and folder path at the same time. It even adds the headers "File" and "Folder" in front of the hyperlinks. Right now my issue with path copy copy is that the short name option does not paste as a hyperlink but other options do. I still have to resort to right clicking in an email, go to link, paste the long folder name into the dialog, and then edit the name that appears (see screenshot).

![image](https://user-images.githubusercontent.com/110548745/182640902-c9be8f02-4659-4d29-b242-50d79d82b12f.png)
![image](https://user-images.githubusercontent.com/110548745/182641272-99c9bb24-ace7-4756-9e9d-74c4daf0c326.png)
![image](https://user-images.githubusercontent.com/110548745/182641460-a82b1dee-2910-46a4-bb52-d4364d62fe1c.png)

**Describe the solution you'd like**
To be able to right click on a file and be able to copy the file name and file location at the same time and paste file name and file location at the same time with the file name working as a hyperlink. Maybe an option that copies the file path in the background but only shows the file name when pasted

![image](https://user-images.githubusercontent.com/110548745/182639799-207bc51f-5c90-4c3d-8452-13b2a0b46776.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by clechasseur** [comment] 2022-08-04 00:37
What you need is to be able to copy a hyperlink with custom display text. This is a more or less a duplicate of #153 , so I'll close this one.

**Closed as not planned by clechasseur** 2022-08-04 00:37 UTC
Labels: enhancement
