### ISSUE TITLE
[BUG] File name not posting as link

### ISSUE THREAD

**Issue by Rafaelmartinezhok** [clechasseur/pathcopycopy#155] opened 2022-08-03 14:46 UTC
**Describe the bug**
I have the "copy short name" checked on the settings as well as the carats "<>" to allow to post as a link. It works fine and pastes like a link when I have the  parent folder path checked but not with "copy short name".

**To Reproduce**

**Expected behavior**
I would like for the "copy short name" to be able to post as a hyperlink. Perhaps code could be altered to copy the entire path name in the background but only show the file name as a hyperlink. 

**Screenshots**
![image](https://user-images.githubusercontent.com/110548745/182637122-47329767-4449-4318-bf68-0d3a98d2606e.png)
![image](https://user-images.githubusercontent.com/110548745/182637163-cf2b5848-9138-421a-81e0-8f640c6b7ebe.png)

**Software (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Path Copy Copy Version [e.g. 17.1]

**Additional context**

**Comment by clechasseur** [comment] 2022-08-04 00:35
This is not really a bug, as the option to add < and > works as expected. What you want is basically a new feature to paste hyperlinks with a text that is different from the link itself. This is thus a duplicate of #156 . I'll close this one.

**Closed as not planned by clechasseur** 2022-08-04 00:35 UTC
Labels: bug
