### ISSUE TITLE
[FEATURE] Support DPI scaling

### ISSUE THREAD

**Issue by mdmower** [clechasseur/pathcopycopy#131] opened 2020-08-25 17:06 UTC
**Is your feature request related to a problem? Please describe.**

The Path Copy Copy settings panel has blurry text:

![image](https://user-images.githubusercontent.com/264920/91205120-e98ea780-e6b9-11ea-86e8-3f100dfc57c6.png)

**Describe the solution you'd like**

Support DPI scaling: https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows

**Describe alternatives you've considered**

Have not considered alternatives since I don't need to access settings very often.

**Additional context**

In the above screenshot, I am using 125% scaling with a resolution of 2560x1440. This is Windows 10 Pro Build 2004.

![image](https://user-images.githubusercontent.com/264920/91205430-6752b300-e6ba-11ea-93e3-b021b289ea39.png)

**Comment by clechasseur** [comment] 2021-07-26 02:04
This is trickier than it looks because the Settings application is built in old Windows Forms technology. Apparently, automatic high DPI support is provided for Windows Forms app starting with .NET Framework 4.7 in some versions of Windows 10:

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

I think it's possible to use this and still work in previous OSes, but then I'd have to target .NET Framework 4.7. I don't know how much of a hassle this would cause to some people... Path Copy Copy is still supported on Vista and up in theory.

I'll keep this open and see.

**Comment by clechasseur** [comment] 2021-08-18 01:12
I've created a branch to test high DPI support. This is a branch of the future 20.0 version, requiring .NET Framework 4.7 and an updated Windows 7.

https://github.com/clechasseur/pathcopycopy/suites/3526182957/artifacts/84270118

@mdmower If you're still interested 😉 , could you try to install this build and see if it works on your side? All I've done is declare high DPI support, so right now some texts are cropped because the forms aren't well adjusted to the new DPI.

**Comment by mdmower** [comment] 2021-08-18 19:21
That's great, thanks for working on this @clechasseur . I will pull the branch tonight (I'm in US PDT time zone) and see how the dialog looks.

**Comment by mdmower** [comment] 2021-08-19 01:54
@clechasseur - feature looks to be coming along well.
Windows 10 64-bit with .NET Framework 4.7.

Sample screenshots when 125% scaling is active:
![image](https://user-images.githubusercontent.com/264920/129994996-246be9d6-2598-4c62-8f3a-a98ac1cc2e51.png)
![image](https://user-images.githubusercontent.com/264920/129995022-0da2f442-ae8a-49d9-be7c-504309bf5c6f.png)
![image](https://user-images.githubusercontent.com/264920/129995035-d73deff4-9603-4500-b597-c833736a02be.png)

Branch HEAD was at 20862d75334fcf28af3ac8be0d15c389634628cf when I compiled.

**Comment by mdmower** [comment] 2021-08-19 02:11
Something that may need a bit more attention is form resizing when the window transitions between monitors with different scaling. If I start the application on a monitor with 125% scaling and drag it to a monitor with 100% scaling (i.e. not scaled), then the settings window looks like the following. It stays this way even after dragging back and forth between the two screens.

![image](https://user-images.githubusercontent.com/264920/129996555-8fcc54cb-c592-4d81-bf9f-1298d3fa72cf.png)

**Comment by clechasseur** [comment] 2021-08-19 02:56
> @clechasseur - feature looks to be coming along well.
> Windows 10 64-bit with .NET Framework 4.7.
> 
> Sample screenshots when 125% scaling is active:

<snip>

Did you resize the windows before taking these screenshots? Here, with the default window size, some of the captions are truncated.

**Comment by clechasseur** [comment] 2021-08-19 02:57
> Something that may need a bit more attention is form resizing when the window transitions between monitors with different scaling. If I start the application on a monitor with 125% scaling and drag it to a monitor with 100% scaling (i.e. not scaled), then the settings window looks like the following. It stays this way even after dragging back and forth between the two screens.

Hmm, I'll have to dig out my old external monitor to test this one.. Might take a bit more time.

**Comment by mdmower** [comment] 2021-08-19 03:56
>Did you resize the windows before taking these screenshots? Here, with the default window size, some of the captions are truncated.

Nope, did not resize. Just looked again, but I'm not seeing truncated text after resizing large and then shrinking down to its smallest allowed size. I'm not exactly clear on what you mean by "caption" though.

**Comment by clechasseur** [comment] 2021-08-21 02:31
I tried hooking up my laptop to my TV today. Here's how the app looks on the TV at 150% scaling.

Not everything is scaled properly it seems. And on all forms other than the main form, it looks like everything is scaled wrong.

![image](https://user-images.githubusercontent.com/1435551/130307746-48302a0b-0372-4363-9565-ea8f08b433b9.png)
![image](https://user-images.githubusercontent.com/1435551/130307754-6e8b50c5-5ce0-4147-9865-6e6c864fb1d2.png)
![image](https://user-images.githubusercontent.com/1435551/130307760-5225be85-14b4-4eb8-82c8-644db6ebef9e.png)
![image](https://user-images.githubusercontent.com/1435551/130307771-71f77ba7-0167-47ba-b819-053d328c325d.png)
![image](https://user-images.githubusercontent.com/1435551/130307778-06431465-ea42-4b72-9d73-0c44a4263c59.png)
![image](https://user-images.githubusercontent.com/1435551/130307781-79d11123-8eb1-465d-bd32-6c552a1a4bb2.png)
![image](https://user-images.githubusercontent.com/1435551/130307785-8ed7341d-89fb-441d-81cd-d412e979832a.png)
![image](https://user-images.githubusercontent.com/1435551/130307790-b07e9219-9f8a-4ba0-a2aa-e60a201a47e7.png)
![image](https://user-images.githubusercontent.com/1435551/130307791-197324d4-f279-40ee-bd17-62702a663785.png)

**Comment by clechasseur** [comment] 2021-08-21 02:34
> Something that may need a bit more attention is form resizing when the window transitions between monitors with different scaling. If I start the application on a monitor with 125% scaling and drag it to a monitor with 100% scaling (i.e. not scaled), then the settings window looks like the following. It stays this way even after dragging back and forth between the two screens.

I reproduced this when I hooked up my laptop to my TV. Laptop screen was at 100%, TV was at 150%. Dragging window between screens broke their content. I have no idea why that is though - I'll try to do some research, but this looks like something that the framework should take care of...

**Comment by clechasseur** [comment] 2021-08-21 03:58
It seems that targeting .NET Framework 4.8 (instead of 4.7) partially fixes the issue of dragging forms between screens with different DPI.

@mdmower Could you grab the latest build and see if it's better on your side? If you don't want to recompile it, you can grab this installer:

https://github.com/clechasseur/pathcopycopy/suites/3557293333/artifacts/85342936

**Comment by clechasseur** [comment] 2021-08-28 00:23
I merged the branch for this issue in `default`. This will be part of the next release.

If more work is needed on this in the future, it will be possible to open a new ticket, but I consider the support we have now to be pretty good (or at least good enough).

**Closed as completed by clechasseur** 2021-08-28 00:23 UTC
Labels: enhancement
