### ISSUE TITLE
[BUG] PathCopy not showing in context menu of Windows 11 23H2

### ISSUE THREAD

**Issue by User-Smith8989** [clechasseur/pathcopycopy#180] opened 2024-04-18 01:39 UTC
**Describe the bug**
PathCopy not showing in context menu of Windows 11 23H2

**Comment by krzysiekk3** [comment] 2024-07-08 06:43
Hello @clechasseur 

Unfortunately, due to this bug, the application is unusable.
**Will the PathCopyCopy application still be updated or has it already been abandoned?**

Still, thanks for all the time I was able to spend with this add-on - it made working with many files/folders a lot easier. ✌️

**Comment by clechasseur** [comment] 2024-07-08 14:41
> **Describe the bug** PathCopy not showing in context menu of Windows 11 23H2

This is the version that I have on my new computer and Path Copy Copy works on mine. Just to make sure, did you select _Show more options_ in the first contextual menu? Path Copy Copy is not Windows 11-ready yet, so you have to switch to the full contextual menu to see it. (See screenshots below - the interface is in French, but the menu options should be the same.)

<img src="https://github.com/clechasseur/pathcopycopy/assets/1435551/d60ce656-fc6f-46c2-8e10-66f989fa0d68" width="300"/>

<img src="https://github.com/clechasseur/pathcopycopy/assets/1435551/5fcfa964-eac9-48f1-afeb-bf89f6ecbca4" width="300"/>

**Comment by clechasseur** [comment] 2024-07-08 14:55
> **Will the PathCopyCopy application still be updated or has it already been abandoned?**

I haven't given up on it yet, but the issue is that for a long time, I no longer had access to a working Windows development machine (my old Windows laptop was just too slow and unusable for that, and it didn't support Windows 11). I _just_ got a new Windows 11 laptop, so I'm hoping to find time to start working on it again. Don't hold your breath, but hopefully 🙂

**Comment by krzysiekk3** [comment] 2024-07-09 14:18
> I haven't given up on it yet, but the issue is that for a long time, I no longer had access to a working Windows development machine (my old Windows laptop was just too slow and unusable for that, and it didn't support Windows 11). I _just_ got a new Windows 11 laptop, so I'm hoping to find time to start working on it again. Don't hold your breath, but hopefully 🙂

Good to hear it!
Tomorrow I'll try to detail what the problem is because I think I have a new clue.... :)
I'll have to check it quietly.

**Comment by krzysiekk3** [comment] 2024-07-11 09:42
Hello @clechasseur 
I noticed a strange thing.

### 1. When installing PathCopyCopy from **winget** in CMD:
`winget install CLechasseur.PathCopyCopy`
![image](https://github.com/clechasseur/pathcopycopy/assets/140146836/41d2649d-b789-4f1a-8dbd-a79a0137e875)

The folder with the installation is located here:
`%LocalAppData%\Programs\Path Copy Copy`
Then the contextual menu does not work.

### 2. On the other hand, install directly from the file - **PathCopyCopy20.0.exe**.
The package installs into Program Files:
`C:\Program Files\Path Copy Copy`
Then the contextual menu works properly. :)
![image](https://github.com/clechasseur/pathcopycopy/assets/140146836/af20ca45-1275-4770-a909-641b46128fd6)


---------------------------------------------------------
Do you have control over the Winget command that the package also installs correctly, or has the right to add itself to the context menu?

FYI - Other applications that install this way add themselves correctly to the RMB Menu. :)

PS
If you need any tests, I will be happy to help. In the meantime, I leave tomorrow for vacation, so contact with me will be in a month.

**Comment by clechasseur** [comment] 2024-07-11 17:40
@krzysiekk3 I did not create the WinGet manifest for Path Copy Copy. However, I perused it and it looks OK. The main difference is that when installing via WinGet, it passes `/CURRENTUSER` to the installer, which installs for current user only.

So I would like for you to try this:
1. Uninstall Path Copy Copy completely. (If uninstaller asks you to reboot, do so.)
2. Using the installer you downloaded manually, re-install, but choose the option to install for current user only.

Then check if Path Copy Copy works as expected. If not, we can move to further diagnostics.

**Comment by krzysiekk3** [comment] 2024-07-12 06:23
@clechasseur Your suspicions are confirmed, manual installation for Current User has the same effect as with Winget - it does not work :)
![2024-0712_08-07-24_PathCopyCopy20 0 tmp](https://github.com/user-attachments/assets/8386d327-a082-4035-be0b-1dfd32be30e7)

**Comment by clechasseur** [comment] 2024-07-12 21:55
@krzysiekk3 It's good that it fails in the same way. (Failure is bad, but consistent failure is better than intermittent failure 😉)

Now: using the Registry Editor (`regedit`), can you confirm that the following keys exist:
* `HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\PathCopyCopy`
  * (note: here, `*` is an actual star character, not a wildcard placeholder for something else)
* `HKEY_CLASSES_ROOT\CLSID\{82CB99A2-2F18-4D5D-9476-54347E3B6720}\InprocServer32`

Also, in that last key, the default value should contain the path to the Path Copy Copy DLL. Something like this:

```
C:\Users\<username>\AppData\Local\Programs\Path Copy Copy\PCC64.dll
```

Can you confim that it does point to the actual local Path Copy Copy DLL?

**Comment by krzysiekk3** [comment] 2024-07-31 06:13
@clechasseur 

I'm sorry for not getting back to you sooner (I was on vacation).

Funny thing, as I have now installed PathCopyCopy on two computers using winget (current user only) --- everything works. 
Maybe in the meantime Microsoft released some fix in Cumulative Update.

For a complete summary, screenshots below :)
![2024-0731_08-12-33_explorer](https://github.com/user-attachments/assets/4de66226-621a-4bd8-b1dc-ab0038ff37f7)

![image](https://github.com/user-attachments/assets/dc0a0d4f-72d5-4c88-8c9a-a55e43710f31)

![image](https://github.com/user-attachments/assets/a0608808-00a4-4c34-af41-c6fa9020f001)

![image](https://github.com/user-attachments/assets/d88f1207-a7e7-4f65-824a-7f1bb3aea5fa)

Best regards!

**Comment by clechasseur** [comment] 2024-07-31 06:17
Sounds good. I'll close this; support for Windows 11 is already covered by #169 .

**Closed as completed by clechasseur** 2024-07-31 06:17 UTC
Labels: bug, waiting for input
