### ISSUE TITLE
[FEATURE] Can set the absolute path for copying files with shortcut keys

### ISSUE THREAD

**Issue by zss823158062** [clechasseur/pathcopycopy#112] opened 2020-03-08 01:33 UTC
Can set the absolute path for copying files with shortcut keys，so as to achieve fast copy

**Comment by clechasseur** [comment] 2020-03-09 00:46
I don't understand what you mean by "set the absolute path for copying files". Path Copy Copy does not copy files, it copies paths… Care to expand on your idea?

**Comment by RotorStator** [comment] 2020-03-14 06:20
Bonjour Charles,

Je comprends pour ma part la demande d'un ajout de raccourci clavier aux menus/ à un menu de PathCopyCopy puisque c'est pour accélérer la copie. mais je comprends peut-être mal.

I understand the request for adding shortcut to a menu or to all menus to do fast copy. But maybe I misunderstand.

![copycopy](https://user-images.githubusercontent.com/60708445/76676458-02037d80-65c4-11ea-87cf-3a4e31651ffb.jpg)

**Comment by clechasseur** [comment] 2020-03-14 20:48
> Je comprends pour ma part la demande d'un ajout de raccourci clavier aux menus/ à un menu de PathCopyCopy puisque c'est pour accélérer la copie. Mais je comprends peut-être mal.

Yes, that's an oft-requested feature (see #3 ), but I haven't found a way to do it so far. However, the original poster mentioned "fast copy", which confused me.

**Comment by clechasseur** [comment] 2020-06-28 01:57
Duplicate of #3 , closing.

**Closed by clechasseur** 2020-06-28 01:57 UTC
Labels: enhancement
