### ISSUE TITLE
[BUG] Broken Feature - After recent Windows 10 Update no longer copies .URL path

### ISSUE THREAD

**Issue by discovery747** [clechasseur/pathcopycopy#128] opened 2020-08-16 21:23 UTC
**Describe the bug**
= = = START
After the recent Windows 10 Update no longer copies ".URL local PC files path" - ID_20200817_002249
example ...
"D:\Path Copy Copy - Internet GitHub Download Shortcut.URL"
as ...
"D:\Path Copy Copy - Internet GitHub Download Shortcut" as it used to - let aside it never copied with the ".URL" suffix as it did/does eg for ".JPG" files ...
as a result, I now (again) as in some Windows 7 times I have to create an associated ".TXT" file and copy path of that ...
example ...
"D:\Path Copy Copy - Internet GitHub Download Shortcut.TXT"
= = = END

**To Reproduce**
= = = START
I believe was already explained above ...
= = = END

**Expected behavior**
= = = START
I believe was already explained above ...
= = = END

**Screenshots**

**Software (please complete the following information):**
 - OS: [Windows 10 - 2004 Build 19041.450 May 2020 update] as installed today 20200815_092929 
 - Path Copy Copy Version 19

![xxAdrian_20200817_001309 WinVer that broke  URL Path Copy Copy functionality](https://user-images.githubusercontent.com/33941787/90344022-8a2bfa00-e01e-11ea-8f14-c6b7780d7221.jpg)

**Additional context**
= = = START
Thank You Very Much for this GREAT Software ...!
(also,) A Feature Request to SORT multiple File/Folder Names, File/Folder Path will follow as a separate GitHub submission ...!
= = = END

**Comment by clechasseur** [comment] 2020-08-17 00:24
Using regedit, can you navigate to the `HKEY_CLASSES_ROOT\.url` key and tell me what the association is (the default value in that key)?

**Comment by discovery747** [comment] 2020-08-23 23:56
I believe it says "InternetShortcut" ...! Sorry for the delay, I am new to GitHub - I will look to set up notifications somehow ...! Thank You, Sir ...!
![xxAdrian_20200824_025319  ComputerHKEY_CLASSES_ROOT URL InternetShortcut](https://user-images.githubusercontent.com/33941787/90991911-2ae95f00-e5b5-11ea-8a94-a159745fada5.jpg)

**Comment by clechasseur** [comment] 2020-08-24 00:16
No problem. I know what the problem is. Leaving this open.

**Comment by discovery747** [comment] 2020-08-24 00:23
You are FAST Sir ...! THANK YOU ...!

How about the other "Feature Request" to SORT multiple ...? Any chance or is it HARD or IMPOSSIBLE (say currently)?
https://github.com/clechasseur/pathcopycopy/issues/129

**Comment by clechasseur** [comment] 2020-08-25 00:38
> How about the other "Feature Request" to SORT multiple ...? Any chance or is it HARD or IMPOSSIBLE (say currently)?
> #129

Yes, I think it's possible. I left it open and will look at it.

**Comment by discovery747** [comment] 2020-08-25 18:40
THANK YOU VERY MUCH ...! THIS WOULD BE GREAT ...!

**Comment by discovery747** [comment] 2020-08-30 21:59
Dear Friend, I do not mean to bug you, however, I dare to ask ay time frame or how are we progressing on this issue (Path Copy Copy no longer working on .URL files) ...? 
As well the suggestion to Sort Internally Multiple Selections ...?
Thank You Very, Very Much ...! Appreciate your kind reply ...!

**Comment by discovery747** [comment] 2020-10-28 02:25
Sir, Dear Sir, I hope you are well, (very) well ...!

I am (by now?) rightly concerned that you might (perhaps?) be upset in some way - or (perhaps) rightly await support (from my side) while I am not there (at least as of) yet, etc - or that you are very busy (as we all fortunately or unfortunately or both are) - or that you cannot currently place my suggestion high enough in your busy To-Do list ...!?

In any way, in/via Path Copy Copy you managed to create a GREAT piece of software (to my taste, habits, etc) and it would be a pity not to continue doing so - as to my current knowledge you are the only one in the World thinkig of this and having done something majorly important about such issue/problem...!

I sincerely hope you are doing not well but great and help us further with your talent ...!

I am not important, however here is more about me at least ...
[https://www.facebook.com/adrian.militaru.747 ](url)
[https://www.ted.com/profiles/5164024/about](url)
[https://docs.google.com/document/d/1vpdP1A1nkv3BXe11fQSST0VhUgFgSiXdA67-0vB0ojc/edit](url) - Adr Electronic Business Card  
It seems to me external links are not supported, worse, perhaps not welcome, etc? - as testing the links, they default still inside GitHub - I will have to learn the hard way-  via some sort of ban? - about this - it does not seem to say so explicitly - however, nor do the links work - we'll do, wait and see later I guess (is 20201028_043452) here ...!

I hope in a sentiment of all, we love to hear from you ...!

Sincerely wishing you well, you a Great Day and a Great Life further on, etc ...!

**Comment by clechasseur** [comment] 2021-02-13 01:30
This should be fixed in the next release.

**Closed as completed by clechasseur** 2021-02-13 01:30 UTC
Labels: bug
