### ISSUE TITLE
Disable "Check for updates automatically" doesn't work

### ISSUE THREAD

**Issue by Amar0g** [clechasseur/pathcopycopy#95] opened 2019-10-16 05:34 UTC
Dear Clechasseur, 

I'm using your soft and it's really great. The only issue I get is with the auto check for update. 
I disabled this option but Path Copy Copy is still showing me there is a new update available. 

![image](https://user-images.githubusercontent.com/18593496/66890631-0c0a5b80-efe7-11e9-8249-e411b99cfade.png)

Best regards , 
Amar0g

**Comment by clechasseur** [comment] 2019-10-16 13:40
What version are you currently using?

Using `regedit`, can you navigate to the following key:

`HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy`

and validate that there is a value named `DisableSoftwareUpdate` with value `1`?

**Comment by clechasseur** [comment] 2019-10-16 13:59
Can you check if it exists in the following keys instead (if they exist):

`HKEY_LOCAL_MACHINE\Software\clechasseur\PathCopyCopy`
`HKEY_LOCAL_MACHINE\Software\Wow6432Node\clechasseur\PathCopyCopy`

**Comment by Amar0g** [comment] 2019-10-16 14:01
I can confirm, it exists in `HKLM \Software\clechasseur\PathCopyCopy`

but not in Wow6432Node

**Comment by clechasseur** [comment] 2019-10-16 14:04
Did you initially install Path Copy Copy using the .msi installer that once existed, by any chance? Other perhaps via Chocolatey? I'm not sure how it ended up there.

What version of Windows are you using? 32-bit or 64-bit?
Are you using an alternate Windows Explorer?

In the meantime, try creating the value in HKCU and see if it stops offering you the update.

**Comment by Amar0g** [comment] 2019-10-21 07:08
Hi , 
Sorry for the delay. 

So currently I'm installing the software with this command : "PathCopyCopy17.0.1.exe" /VERYSILENT /SUPRESSMSGBOXES /NORESTART

I'll edit the registry. 

Best regards,

**Comment by clechasseur** [comment] 2019-10-21 13:18
> So currently I'm installing the software with this command : "PathCopyCopy17.0.1.exe" /VERYSILENT /SUPRESSMSGBOXES /NORESTART

Hmm, that still doesn't explain how the setting got in HKLM. Weird.

> Edit : In my folder I have a settings.reg file in the same folder than the installer. Do you have an option that 'll check if a settings.reg file is available in the same folder than the installer and apply the settings in the registry ? If yes, I guess the issue is linked to this file. But I cannot remember where it came from. Or, maybe, this file is just a backup I made.

No, the installer does not check for such a .reg file.

Let me know if creating the value in HKCU fixes the issue or not. I'll leave this open, as it still doesn't explain why update checks are performed when the updates are disabled globally.

**Comment by clechasseur** [comment] 2020-01-04 05:10
I've tested this locally and if updates are disabled, the update dialog does not appear. However, I thought of some possible scenarios which would cause this, but it involves using shells with different bitness.

Since I did not hear back about this, I'll close this until we can get a reproducible scenario.

**Closed by clechasseur** 2020-01-04 05:10 UTC
Labels: bug
