### ISSUE TITLE
Suggestion: copy .lnk paths!

### ISSUE THREAD

**Issue by zeb0z** [clechasseur/pathcopycopy#41] opened 2018-06-13 17:38 UTC
It would be nice to be able to copy the paths of .lnk (shortcut) files, not just the target of what the shortcut points to.  Thanks

**Comment by thedoctrine101** [comment] 2018-06-15 01:43
Good idea. Some shortbut properties dialog box do not show the target field for some reason. This feature would circumvent that where applicable. I support this enhancement idea.

**Comment by clechasseur** [comment] 2018-06-18 00:37
Just realized this is a duplicate of #7 . Closing this one.

**Closed by clechasseur** 2018-06-18 00:37 UTC
Labels: duplicate, enhancement
